#version 460 core

layout(location = 0) in vec3 a_position;
layout(location = 1) in vec3 a_normal;
layout(location = 2) in vec2 a_uv;

uniform mat4  u_view;
uniform mat4  u_proj;
uniform float u_time;
uniform float u_scene_norm;   // 0..1 within Scene 3
uniform float u_beat;

out vec3  v_world_pos;
out vec3  v_normal;
out vec2  v_uv;
out float v_instance_id;
out float v_corruption;

// Hash helpers — reproducible per building from world XZ position
float hash1(float n)  { return fract(sin(n) * 43758.5453); }
float hash2(vec2 p)   { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }

void main() {
    // Building geometry is already in world space (generated by build_city).
    // Derive per-building variation from the XZ grid cell so all parts of the
    // same building complex share the same corruption/displacement rate.
    vec3 world_pos = a_position;

    // Cell size ~8 world units — large enough that fins/cornices on the same
    // building share the same cell, small enough to give per-block variation.
    vec2 cell = floor((world_pos.xz + 0.5) / 8.0);
    float fi  = hash2(cell) * 1000.0;   // unique float per grid cell

    // Per-building corruption rate: some buildings corrupt sooner/harder
    float rate       = 0.25 + hash1(fi * 13.7f) * 0.75f;
    float corruption = rate * u_scene_norm;

    // Sinusoidal Y-axis bending — buildings warp toward mathematical forms
    float disp_scale = corruption * corruption;
    float bend_x = sin(world_pos.y * 0.5 + u_time * 0.8 + fi * 0.0013) * disp_scale * 0.4;
    float bend_z = cos(world_pos.y * 0.5 + u_time * 0.7 + fi * 0.0021) * disp_scale * 0.3;
    world_pos.x += bend_x;
    world_pos.z += bend_z;

    // Beat-sync jolt on strong beats
    float jolt = smoothstep(0.04, 0.0, u_beat) * disp_scale * 0.1;
    world_pos.x += sin(fi * 7.3) * jolt;
    world_pos.y += jolt * 0.2;
    world_pos.z += cos(fi * 5.1) * jolt;

    v_world_pos   = world_pos;
    v_normal      = a_normal;
    v_uv          = a_uv;
    v_instance_id = fi;
    v_corruption  = corruption;

    gl_Position = u_proj * u_view * vec4(world_pos, 1.0);
}
